{{- $pw := (include "syncthing.password" .) | fromJson }}
{{- if and $pw.create $pw.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pw.name }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.env.PASSWORD | default (randAlphaNum 40) }}
{{- end }}
