{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "syncthing.fullname" . }}-sa
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
{{- end }}
