apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  labels:
    app: wikijs
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
data:
  config.yml: |
    port: 3000
    bindIP: 0.0.0.0
    db:
      type: postgres
      host: '$(DB_HOST)'
      port: '$(DB_PORT)'  
      user: '$(DB_USER)'
      pass: '$(DB_PASS)'
      db: '$(DB_NAME)'
      ssl: false
    dataPath: ./data
    logLevel: info
