apiVersion: v2
name: syncthing
description: Helm chart for syncthing
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: istio-ingress
    version: 0.1.0
    repository: https://mbround18.github.io/helm-charts
    condition: istio-ingress.enabled
