{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.postgresql.passwordSecret }}
{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.passwordSecret }}
stringData:
  POSTGRES_PASSWORD: {{ index $secret.data "POSTGRES_PASSWORD" | b64dec }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.passwordSecret }}
stringData:
  POSTGRES_PASSWORD: {{ randAlphaNum 32 }}
{{- end }}
