{{- if .Values.secrets.superuserPassword.create }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.secrets.superuserPassword.name }}
{{- if $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.superuserPassword.name }}
  annotations:
    {{- with .Values.global.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  POSTGRES_PASSWORD: {{ index $secret.data "POSTGRES_PASSWORD" | b64dec }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.superuserPasswordSecret }}
  annotations:
    {{- with .Values.global.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  POSTGRES_PASSWORD: {{ randAlphaNum 32 }}
{{- end }}
{{- end }}
