{{- if .Values.provisioning.enabled }}
{{- $indexSecret := lookup "v1" "Secret" .Release.Namespace .Values.provisioning.indexSecret }}
{{- $apiKey := "" }}
{{- if and $indexSecret (index $indexSecret.data "api-key") }}
  {{- $apiKey = index $indexSecret.data "api-key" | b64dec }}
{{- else }}
  {{- $apiKey = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.indexSecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Delete=false
stringData:
  api-key: {{ $apiKey }}
{{- end }}
