{{- if .Values.provisioning.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meilisearch.fullname" . }}-provisioner-scripts
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
    main.py: |
{{- .Files.Get "./resources/main.py" | indent 6 }}
    pyproject.toml: |
{{- .Files.Get "./resources/pyproject.toml" | indent 6 }}
{{- end }}