{{- if .Values.provisioning.enabled }}
{{- $indexSecret := lookup "v1" "Secret" .Release.Namespace .Values.provisioning.indexSecret }}
{{- if not $indexSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.indexSecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0"
stringData:
  api-key: ""
{{- end }}
{{- end }}
