{{- if .Values.provisioning.enabled }}
{{- $indexSecret := lookup "v1" "Secret" .Release.Namespace .Values.provisioning.indexSecret }}
{{- $apiKey := "" }}
{{- if and $indexSecret (index $indexSecret.data "api-key") }}
  {{- $apiKey = index $indexSecret.data "api-key" | b64dec }}
{{- else }}
  {{- $apiKey = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.indexSecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  api-key: {{ $apiKey }}
{{- end }}
