{{- $masterSecret := lookup "v1" "Secret" .Release.Namespace .Values.auth.masterKeySecret }}
{{- $masterKey := "" }}
{{- if and $masterSecret (index $masterSecret.data "master-key") }}
  {{- $masterKey = index $masterSecret.data "master-key" | b64dec }}
{{- else }}
  {{- $masterKey = randAlphaNum 128 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.masterKeySecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/resource-ignore: "true"
    argocd.argoproj.io/sync-options: Prune=false,Replace=false
stringData:
  master-key: {{ $masterKey }}
