{{- if .Values.secrets.masterKey.create }}
{{- $masterSecret := lookup "v1" "Secret" .Release.Namespace .Values.secrets.masterKey.name }}
{{- $masterKey := "" }}
{{- if and $masterSecret (index $masterSecret.data "master-key") }}
  {{- $masterKey = index $masterSecret.data "master-key" | b64dec }}
{{- else }}
  {{- $masterKey = randAlphaNum 128 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.masterKey.name }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  {{ .Values.secrets.masterKey.key }}: {{ $masterKey }}
{{- end }}