{{- $masterSecret := lookup "v1" "Secret" .Release.Namespace .Values.auth.masterKeySecret }}
{{- if $masterSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.masterKeySecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
stringData:
  master-key: {{ index $masterSecret.data "master-key" | b64dec }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.masterKeySecret }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
stringData:
  master-key: {{ randAlphaNum 128 }}
{{- end }}
