{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "meilisearch.fullname" . }}-ui
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.uiPort }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "meilisearch.selectorLabels" . | nindent 4 }}
{{- end }}
