{{- if .Values.secrets.jwt.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwt.name }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.env.JWT_SECRET_KEY | default (randAlphaNum 40) }}
{{- end }}
