{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "audiobookshelf.fullname" . }}-sa
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
{{- end }}
