apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale.fullname" . }}
  labels:
    {{- include "hytale.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalIPs:
    - {{ .Values.endpoint.externalIP }}
  ports:
    - port: {{ .Values.endpoint.serverPort }}
      targetPort: server-udp
      protocol: UDP
      name: server-udp
    {{- if .Values.endpoint.consolePort }}
    - port: {{ .Values.endpoint.consolePort }}
      targetPort: console-tcp
      protocol: TCP
      name: console-tcp
    {{- end }}
  selector:
    {{- include "hytale.selectorLabels" . | nindent 4 }}
