apiVersion: v2
name: meilisearch
description: A Helm chart for Meilisearch
type: application
version: 0.1.1
appVersion: v1.11.1
dependencies:
- name: istio-ingress
  version: 0.1.0
  repository: file://../istio-ingress
  condition: istio-ingress.enabled
